sudo: required
language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-19

before_script:
  - sudo chmod +x gradlew
