#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNone, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNone, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	float joy1x1;
	float joy1y1;

  motor[motorD] = 200;
  motor[motorE] = 0;

  while (true)
  {
    getJoystickSettings(joystick);

    // Get fresh raw joystick values for left stick

    joy1x1 = joystick.joy1_x1;
    joy1y1 = joystick.joy1_y1;

    // if movement smaller than calibration value (10), set to zero to switch off motors

    if (abs(joy1x1) < 10) joy1x1 = 0;
    if (abs(joy1y1) < 10) joy1y1 = 0;

    if (joy1y1 < 0) joy1x1 = -joy1x1;

    // Motor setting will be a weighted sum of forward/backward and left/right
    // don't want to go backwards unless stick pulled backwards, so need
    // to make sure left/right doesn't dominate the sum, that's why f/b (joy1y1)
    // gets a heavier weighting

    float fbweight = 2;

  	motor[motorD] = (int) ((-1) * (fbweight*joy1y1 + joy1x1) / (fbweight+1)) ;
  	motor[motorE] = (int) ((fbweight*joy1y1 - joy1x1) / (fbweight+1)) ;
  }
}
