#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     touchSensor,         sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
// Eastside Preparatory FTC Robot 1 main robot control code
//

#include "EPS_JoystickDriver.c"
#include "hitechnic-irseeker-v2.h"
#include "EPS_DECLARATIONS.h"
#include "EPS_MUSIC.h"
#include "EPS_DRIVER.h"

void MoveClaw (int amount) {
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorA]= abs(amount);
	nMotorEncoderTarget[motorB]= abs(amount);

	motor[motorA] = (amount >0 ? 20:-20);
	motor[motorB] = (amount >0 ? 20:-20);
	int i = 5000;
	while (nMotorRunState[motorA] != runStateIdle && nMotorRunState[motorB] != runStateIdle && i > 0) {
		i-= 1;
	}
	motor[motorA] = 0;
	motor[motorB] = 0;
}

void EPS_initialize () {
	// initialization after power up and before autonomus period
	// we may put servos into a certain position etc. here
	// if we do antyhing here, don't for get to put the "robot moves during init" label on the robot!!!

	EPS_WeAreTheChampions ();
	//	nSyncedMotors = synchAB;
	//	nSyncedTurnRatio = -100;

	//MoveClaw(-20);
	//wait10Msec (100);
	//MoveClaw(20);
}

void EPS_autonomous_work () {
	if(true) {
		EPS_Housework();
		motor[motorD] = 0;
		motor[motorE] = 0;
		//forward
		motor[motorD] = -50;
		motor[motorE] = 50;
		wait10Msec(50);
		CHECK_FOR_STOP();
		//stop and close claw
		motor[motorD] = 0;
		motor[motorE] = 0;
	}
}

void EPS_autonomous () {
	EPS_autonomous_work();
	motor[motorD] = 0;
	motor[motorE] = 0;
	return;
}

task main() {
	bool bAutoDone = false;
	EPS_initialize ();
	//EPS_autonomous_work();
	while (true) {
		waitForStart ();

		getJoystickSettings(joystick);
		if (joystick.UserMode || bAutoDone) {
			EPS_driver_control();
		}
		else {
			EPS_autonomous ();
			bAutoDone = true;
		}
	}
}
