#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase
  int joyvalueX[] = {-90,-45,45,90};
	int joyvalueY[] = {-90,-45,45,90};

	int motorDMatrix[5][5] = {{100,0,100,0,-100},
	  											 {40,0,0,0,0},
	  											 {100,0,0,0,-100},
	  											 {-40,0,0,0,0},
	  											 {0,0,-100,0,0}};
	int motorEMatrix[5][5] = {{0,0,-100,0,0},
	  											 {0,0,0,0,40},
	  											 {100,0,0,0,-100},
	  											 {0,0,0,0,-40},
	  											 {100,0,100,0,-100}};
  while (true)
  {
  	float joy1x1 = joystick.joy1_x1;
		float joy1y1 = joystick.joy1_y1;

	  if (joy1x1 > joyvalueX[0] && joy1y1 > joyvalueY[3]) {
	  	motor[motorD] = motorDMatrix[0][0];
	  	motor[motorE] = motorEMatrix[0][0];
		}
		if (joy1x1 > joyvalueX[1] && joy1x1 < joyvalueX[0] && joy1y1 > joyvalueY[3]) {
	  	motor[motorD] = motorDMatrix[1][0];
	  	motor[motorE] = motorEMatrix[1][0];
		}
		if (joy1x1 < joyvalueX[1] && joy1x1 < joyvalueX[2] && joy1y1 > joyvalueY[3]) {
	  	motor[motorD] = motorDMatrix[2][0];
	  	motor[motorE] = motorEMatrix[2][0];
		}
		if (joy1x1 > joyvalueX[2] && joy1x1 < joyvalueX[3] && joy1y1 > joyvalueY[3]) {
	  	motor[motorD] = motorDMatrix[3][0];
	  	motor[motorE] = motorEMatrix[3][0];
		}
		if (joy1x1 > joyvalueX[3] && joy1y1 > joyvalueY[3]) {
	  	motor[motorD] = motorDMatrix[4][0];
	  	motor[motorE] = motorEMatrix[4][0];
		}
  }
}
